### ISSUE TITLE
Objective C version

### ISSUE THREAD

**Issue by Manueldjz** [Binur/SubscriptionPrompt#4]
how this use this code in objective c......?
Any example :)
Thanks

**Comment by binchik** [comment]
The same way as in Swift, just install via cocoapods, use the following SubscriptionViewController `init`: 
`
(title: String? = nil, slides: [Slide], options: [Option],
    cancelMessage: String? = nil, restoreButtonTitle: String? = nil)
`
finally present using `presentViewController` method
