### ISSUE TITLE
Update to Swift 3.2 & 4 request.

### ISSUE THREAD

**Issue by Kaakati** [Binur/SubscriptionPrompt#7]
Please update to Swift 3.2 & 4

**Comment by nitishmakhija** [comment]
#6 Refer to this
This has been merged into master itself.

**Comment by binchik** [comment]
Hello @nitishmakhija Did you run your PR successfully? I am getting errors with `pod lib lint`. Sorry have not been developing for iOS for the past year, I may be missing something.

**Comment by binchik** [comment]
Thanks everyone, Swift 3 support is added in 1.0.1. It is already available in CocoaPods.

**Comment by nitishmakhija** [comment]
@binchik I did check that's why I submitted the PR.
